-- Test the local version of the module:
package.path = "../src/?.lua;" .. package.path
local engine = require('template-text')
local test_common = require("common")

local dotest = function(case)
    return test_common.dotest(engine, case)
end

--- These tests exercise the options to control blank/empty lines resulting from
-- runtime evaluation, such as when a replacement field is found to be the empty
-- string in the evaluation environment.
--
-- We test replacement fields $() and table inclusion ${}


local env = {empty=""}

local tpl_with_empty = [[
Lorem ipsum dolor sit amet,
$(empty)$(empty)
consectetur adipiscing elit
]]

local tpl_with_blanks = [[
Lorem ipsum dolor sit amet,
$(empty)  $(empty)
consectetur adipiscing elit
]] -- note the spaces between the empty variables

local expected_with_blanks = [[
Lorem ipsum dolor sit amet,
  
consectetur adipiscing elit
]] -- note the spaces in the midline

local expected_with_empty = [[
Lorem ipsum dolor sit amet,

consectetur adipiscing elit
]]

local expected_with_no_empty = [[
Lorem ipsum dolor sit amet,
consectetur adipiscing elit
]]

dotest( {
    id = "include-empty-line-by-default",
    desc = "by default, a line that evaluates to the empty line should be preserved",
    tpl = tpl_with_empty,
    expected = expected_with_empty,
    env = env,
    opts = {},
} )

dotest( {
    id = "include-empty-line",
    desc = "when using the dedicated option, a line that evaluates to the empty line should be preserved",
    tpl = tpl_with_empty,
    expected = expected_with_empty,
    env = env,
    opts = { preserve={empty=true} },
} )

dotest( {
    id = "exclude-empty-line",
    desc = "when using the dedicated option, a line that evaluates to the empty line should be dropped",
    tpl = tpl_with_empty,
    expected = expected_with_no_empty,
    env = env,
    opts = { preserve={empty=false} },
} )

dotest( {
    id = "include-blanks-by-default",
    desc = "by default, a line that evaluates to blanks only should be preserved",
    tpl = tpl_with_blanks,
    expected = expected_with_blanks,
    env = env,
    opts = {},
} )

dotest( {
    id = "include-blanks",
    desc = "when using the dedicated option, a line that evaluates to blanks only should be preserved",
    tpl = tpl_with_blanks,
    expected = expected_with_blanks,
    env = env,
    opts = { preserve={blank=true} },
} )

dotest( {
    id = "exclude-blanks",
    desc = "with the right options, trailing spaces should be dropped but the empty line preserved",
    tpl = tpl_with_blanks,
    expected = expected_with_empty,
    env = env,
    opts = { preserve={blank=false, empty=true} },
} )

dotest( {
    id = "exclude-blanks-and-empty",
    desc = "with the right options, a line that evaluates only to blanks is dropped altogether",
    tpl = tpl_with_blanks,
    expected = expected_with_no_empty,
    env = env,
    opts = { preserve={blank=false, empty=false} },
} )



-- Tests with a for loop and replacement fields
--

tpl = [[
@for i,v in ipairs({"monkey", "bear", "", "ladybug", "", "salmon"}) do
    $(v)
@end
]]


dotest( {
    id = "drop-leading-spaces-in-forloop",
    desc = "leading spaces in otherwise empty lines generated by a for loop are stripped",
    tpl = tpl,
    expected = [[
    monkey
    bear

    ladybug

    salmon
]],
    env = env,
    opts = { preserve={blank=false, empty=true} },
-- The leading spaces due to the indentation of '$(v)' in the
-- template, are dropped for the empty elements of the list
} )

dotest( {
    id = "drop-leading-spaces-and-empty-lines-in-forloop",
    desc = "blank lines generated by a for loop are dropped",
    tpl = tpl,
    expected = [[
    monkey
    bear
    ladybug
    salmon
]],
    env = env,
    opts = { preserve={blank=false, empty=false} },
} )



-- On the indentation option
-- Programmed indentation is never prepended to empty lines

dotest( {
    id = "indent-option-1",
    desc = "programmed indentation is never prepended to empty lines, even with the preserve-blanks option",
    tpl = [[
AA

  BB
]],
    expected = [[
    AA

      BB
]],
    env = env,
    opts = { preserve={blank=true, empty=false}, indent=4 },
-- note that the middle line does _not_ have the 4 spaces
} )

dotest( {
    id = "indent-option-2",
    desc = "the special token can force preserving the blanks, also those induced by the indent option",
    tpl = [[
AA
${}
  BB
]],
    expected = [[
    AA
    
      BB
]],
    env = env,
    opts = { preserve={blank=false, empty=false}, indent=4 },
} )


-- ------------------------------- --
-- Tests involving table inclusion --
-- ------------------------------- --

-- Missing table-id is special

dotest( {
    id = "missing-tableid-is-placeholder",
    desc = "a table inclusion with no argument is considered a marker to preserve leading blanks unconditionally",
    tpl = [[   ${}]],
    expected = [[   ]],
    env = {},
    opts = { preserve={blank=false, empty=false} },
} )

dotest( {
    id = "missing-tableid-is-placeholder-2",
    desc = "a table inclusion with no argument is considered a marker to preserve leading blanks unconditionally, but no trailing blanks",
    tpl = [[	${}  ]],
    expected = [[	]], -- the blank here is a TAB. Trailing blanks are dropped
    env = {},
    opts = { preserve={blank=false, empty=false} },
} )


-- Relative indentation of a table-inclusion is treated the same way as the
-- indent option of template expansion: it is never prepended if the line would
-- be empty otherwise, regardless of options.
-- So it is ignored for empty lines in the included table, and also for the
-- special case of an empty table in the first place.
-- This makes an empty table different than an empty field (where leading blanks
-- are preserved/dropped depending on the user's options).

env.empty_table={}

local tpl_with_empty_table = [[
Lorem ipsum dolor sit amet,
  ${empty_table}
consectetur adipiscing elit
]]

dotest( {
    id = "table-indentation-not-applied-1",
    desc = "the indentation of an included empty table does not yield to trailing blanks",
    tpl = tpl_with_empty_table,
    expected = expected_with_empty,
    env = env,
    opts = {},
} )

dotest( {
    id = "table-indentation-not-applied-2",
    desc = "the indentation of an included empty table does not yield to trailing blanks, even with the option to preserve the blank characters",
    tpl = tpl_with_empty_table,
    expected = expected_with_empty,
    env = env,
    opts = { preserve={blank=true} },
} )


dotest( {
    id = "exclude-blank-line",
    desc = "an included empty table with leading spaces is completely dropped, when options say so",
    tpl = tpl_with_empty_table,
    expected = expected_with_no_empty,
    env = env,
    opts = { preserve={empty=false} },
} )



-- Tests with a non-empty table that contains blank/empty lines
--


local includeMe = {"table line 1", "    ", "table line 3", "", "table line 5" }
local tpl = [[
First line
${includeMe}
Last line
]]

local expected_preserve_all = [[
First line
table line 1
    
table line 3

table line 5
Last line
]] -- both spaces(blanks) and newlines are there

local expected_preserve_empty = [[
First line
table line 1

table line 3

table line 5
Last line
]] -- only newlines; blanks in line 2 of the table are stripped

local expected_preserve_none = [[
First line
table line 1
table line 3
table line 5
Last line
]] -- blanks and newlines are dropped

env.includeMe = includeMe

dotest( {
    id = "preserve-table-lines",
    desc = "the lines in a table are preserved, including blank and empty lines",
    tpl = tpl,
    expected = expected_preserve_all,
    env = env,
    opts = { preserve={blank=true, empty=true} },
} )

dotest( {
    id = "preserve-table-newlines",
    desc = "empty lines in a table are preserved, but blank characters alone are dropped",
    tpl = tpl,
    expected = expected_preserve_empty,
    env = env,
    opts = { preserve={blank=false, empty=true} },
} )

dotest( {
    id = "drop-table-empty-lines",
    desc = "both space-only and empty lines in a table are dropped",
    tpl = tpl,
    expected = expected_preserve_none,
    env = env,
    opts = { preserve={blank=false, empty=false} },
} )


-- Now the most complex case, when the table is included with leading indentation.


tpl = [[
First line
  ${includeMe}
Last line
]]

dotest( {
    id = "preserve-table-blanks-and-indentation",
    desc = "blank and empty lines in a table are preserved, including source indentation",
    tpl = tpl,
    expected =[[
First line
  table line 1
      
  table line 3

  table line 5
Last line
]],
-- Note that table-line-2 has blanks: the original indentation plus the line content.
-- On the other hand line-4 has nothing: the indentation is never added to empty lines.
    env = env,
    opts = { preserve={blank=true, empty=true} },
} )

dotest( {
    id = "drop-table-blanks-preserve-indentation",
    desc = "blanks are dropped but empty lines in a table are preserved, including source indentation",
    tpl = tpl,
    expected =[[
First line
  table line 1

  table line 3

  table line 5
Last line
]],
    env = env,
    opts = { preserve={blank=false, empty=true} },
} )






-- -------------------------------------------------------------------------- --
-- Stripping blanks/empty lines should only happen when expansion takes place --
-- -------------------------------------------------------------------------- --

-- That is, blanks/empty lines which are inserted literally in the template,
-- must be preserved (because if the user does not want them, he/she can just
-- avoid them in the first place)

tpl = [[
$(empty)

AA
]]

expected = [[

AA
]]

dotest( {
    id = "drop-expanded-empty-lines-but-preserve-static-ones",
    desc = "empty lines in the source template are always preserved",
    tpl = tpl,
    expected = expected,
    env = env,
    opts = { preserve={blank=false, empty=false} },
} )

tpl = [[
Line 1

  ${empty_table}
    
The line above has 4 blank characters
]]

expected = [[
Line 1

    
The line above has 4 blank characters
]]


dotest( {
    id = "drop-expanded-empty-tables-but-preserve-static-ones",
    desc = "empty lines in the source template are always preserved",
    tpl = tpl,
    expected = expected,
    env = env,
    opts = { preserve={blank=false, empty=false} },
} )


-- The next one is tricky..
--
tpl = [[
@for i = 1,3 do
    $(empty)

@end
]]
-- With a template like this, the user wants an empty line to separate the
-- repeated expansions, but most likely he/she wants it _only_ if the expansion
-- actually yields something.
-- However, at the moment we cannot do that: for this example, if we preserve
-- empty lines, we will get six of them. If we drop them, we will still get
-- three, because the options only control the result of expansions. The literal
-- empty line in the template is not affected (by design!)

expected = [[



]]

dotest( {
    id = "",
    desc = "",
    tpl = tpl,
    expected = expected,
    env = env,
    opts = { preserve={blank=false, empty=false} },
} )
